steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/myresume-457817/screenshot-app', '.' ]

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/myresume-457817/screenshot-app' ]

  # Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'screenshot-app' # Change to your Cloud Run service name if needed
      - '--image'
      - 'gcr.io/myresume-457817/screenshot-app'
      - '--region'
      - 'us-central1' # Change to your desired region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi' # Increase memory for PDF generation (up from default 512Mi)
      - '--cpu'
      - '2' # Increase CPU for better performance
      - '--timeout'
      - '300' # 5 minutes timeout for PDF generation
      # - '--service-account'
      # - 'YOUR-SERVICE-ACCOUNT@YOUR-PROJECT.iam.gserviceaccount.com' # Uncomment and set if needed
      - '--project'
      - 'myresume-457817'

images:
  - 'gcr.io/myresume-457817/screenshot-app'

options:
  logging: CLOUD_LOGGING_ONLY 